LaserSite/LaserSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^userpolls/', include('userpolls.urls', namespace='userpolls')),
    url(r'^', include('pages.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

LaserSite/pages/urls.py
__author__ = 'mslavin'
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^home', views.home, name='home'),  # ex: /polls/
    url(r'^create', views.create, name='create'),
    url(r'^contact', views.contact, name='contact'),
]

LaserSite/userpolls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),  # # ex: /polls/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),  # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),  # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),  # ex: /polls/5/vote/
]

LaserSite/pages/models.py
from django.db import models

# Create your models here.

LaserSite/userpolls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text  # https://docs.djangoproject.com/en/1.8/intro/tutorial01/quit()


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

LaserSite/pages/forms.py
__author__ = 'mslavin'

from django import forms


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Your name:"
        self.fields['contact_email'].label = "Your email:"
        self.fields['content'].label = "What do you want to say?"

LaserSite/pages/views.py
from django.shortcuts import render, redirect
from forms import ContactForm
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.template import Context
from django.contrib import messages
from django.contrib.messages import get_messages

def home(request):
    return render(request, 'pages/home.html')  # (request, 'template_name', dictionary(optional))


def create(request):
    return render(request, 'pages/create.html')  # (request, 'template_name', dictionary(optional))


def contact(request):
    form_class = ContactForm
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name', '')
            contact_email = request.POST.get(
                'contact_email', '')
            form_content = request.POST.get('content', '')
            # email the profile with the contact information
            template = get_template('pages/contact_template.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content, })
            content = template.render(context)
            email = EmailMessage("New contact form submission",
                                 content,
                                 "Your website" +'<hi@weddinglovely.com>',
                                 ['youremail@gmail.com'],
                                 headers={'Reply-To': contact_email })
            email.send()
            #messages.add_message(request, messages.SUCCESS, 'Hello world.')
            messages.success(request, "Email sent successfully!")
            get_messages(request)
            return redirect('contact')
    return render(request, 'pages/contact.html', {'form': form_class})

LaserSite/userpolls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Choice, Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'userpolls/home.html', context)  # (request, 'template_name', dictionary(optional))


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'userpolls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'userpolls/results.html', {'question': question})


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'userpolls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('userpolls:results', args=(p.id,)))

LaserSite/pages/templates/pages/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'pages/bootstrap.min.css' %}" />
  <script type="text/javascript" src="{% static 'pages/jquery.js' %}"></script>  <!-- DO NOT CHANGE ORDER! -->
  <script type="text/javascript" src="{% static 'pages/bootstrap.min.js' %}"></script>  <!-- DO NOT CHANGE ORDER! -->
  <script type="text/javascript" src="{% static 'pages/main.js' %}"></script>  <!-- DO NOT CHANGE ORDER! -->

</head>
<body>


<!-- navigation panel -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Laser Print</a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse-main">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#home">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Make Your Print</a></li>
          <li><a href="#google_map">Contact</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div id="home" class="home">
    <div class="text-vcenter">
      <!--<h1>Contact</h1>-->
        <h2>Need to get in touch?</h2>
      <h3>Send us an email below!</h3>
        <br><br>

        {% block content %}
    <form role="form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <!--Need to figure out how to customize buttons-->
        <!--<button type="submit">Submit</button>-->
        <!--<a href="#about" class="btn btn-default btn-lg">About</a>--> <!--Jumbotron HTML-->
       <a href="#submit" class="btn btn-default btn-lg" role="button">Submit</a>


    </form>
    {% endblock %}

    </div>
  </div>


</body>
</html>

LaserSite/pages/templates/pages/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://i.imgur.com/3I1gkkz.png">

    <title>Laser Print</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pages/jumbotron.css' %}" />
    <script type="text/javascript" src="{% static 'pages/jquery.js' %}"></script>  <!-- DO NOT CHANGE ORDER! -->
    <script type="text/javascript" src="{% static 'pages/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'pages/ie10-viewport-bug-workaround.js' %}"></script>
    <script type="text/javascript" src="{% static 'pages/custom.js' %}"></script>
  </head>

  <body>
   <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Laser Print</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav nav-pills">
            <li role="presentation"><a href="#">Home</a></li>
            <li role="presentation"><a href="#">About</a></li>
            <li role="presentation"><a href="#">Create Your Prints</a></li>
          </ul>

        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>About Us</h1>
        <p>This is all about us</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading1</h2>
          <p>paragraph 1</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading2</h2>
          <p>paragraph 2 </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Laser Print</p>
      </footer>
    </div> <!-- /container -->


  </body>
</html>

LaserSite/pages/templates/pages/home.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="utf-8" />
  <meta name="author" content="Script Tutorials" />
  <title>Laser Site</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'pages/bootstrap.min.css' %}" />
  <script type="text/javascript" src="{% static 'pages/jquery.js' %}"></script>  <!-- DO NOT CHANGE ORDER! -->
  <script type="text/javascript" src="{% static 'pages/bootstrap.min.js' %}"></script>  <!-- DO NOT CHANGE ORDER! -->
  <script type="text/javascript" src="{% static 'pages/main.js' %}"></script>  <!-- DO NOT CHANGE ORDER! -->

  <!-- attach JavaScripts -->
  <script src="https://maps.google.com/maps/api/js?sensor=true"></script>

</head>
<body>

  <!-- navigation panel -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Laser Print</a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse-main">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#home">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Make Your Print</a></li>
          <li><a href="#google_map">Contact</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- first section - Home -->
  <div id="home" class="home">
    <div class="text-vcenter">
      <h1>Welcome!</h1>
      <h3>We are Laser Print.</h3>
      <a href="#about" class="btn btn-default btn-lg">About</a>
    </div>
  </div>
  <!-- /first section -->

  <!-- second section - About -->
  <div id="about" class="pad-section">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <img src="http://i.imgur.com/uwAuywJ.jpg" alt="" />
        </div>
        <div class="col-sm-6 text-center">
          <h2>Doing all the things. All the things you need.</h2>
          <p class="lead">And then also doing that other thing.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- /second section -->

  <!-- third section - Services -->
  <div id="services" class="pad-section">
    <div class="container">
      <h2 class="text-center">How does it work?</h2> <hr />
      <div class="row text-center">
        <div class="col-sm-3 col-xs-6">
          <i class="glyphicon glyphicon-heart"> </i>
          <h4>Check us out!</h4>
          <p>Look around, check out some exmaples.</p>
        </div>
        <div class="col-sm-3 col-xs-6">
          <i class="glyphicon glyphicon-floppy-open"> </i>
          <h4>Upload your picture</h4>
          <p>Futz with the coloring if you'd like.</p>
        </div>
        <div class="col-sm-3 col-xs-6">
          <i class="glyphicon glyphicon-hand-up"> </i>
          <h4>Place Order</h4>
          <p>Go wait for mailman</p>
        </div>
        <div class="col-sm-3 col-xs-6">
          <i class="glyphicon glyphicon-heart"> </i>
          <h4>Get your thing</h4>
          <p>And be very happy!</p>
        </div>
      </div>
    </div>
  </div>
  <!-- /third section -->

  <!-- fourth section - Information -->
  <div id="information" class="pad-section">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="panel-title">Additional information</h2>
            </div>
            <div class="panel-body lead">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit adipiscing blandit. Aliquam placerat, velit a fermentum fermentum, mi felis vehicula justo, a dapibus quam augue non massa. Duis euismod, augue et tempus consequat, lorem mauris porttitor quam, consequat ultricies mauris mi a metus. Phasellus congue, leo sed ultricies tristique, nunc libero tempor ligula, at varius mi nibh in nisi. Aliquam erat volutpat. Maecenas rhoncus, neque facilisis rhoncus tempus, elit ligula varius dui, quis amet.
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="panel-title">Additional information</h2>
            </div>
            <div class="panel-body lead">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit adipiscing blandit. Aliquam placerat, velit a fermentum fermentum, mi felis vehicula justo, a dapibus quam augue non massa. Duis euismod, augue et tempus consequat, lorem mauris porttitor quam, consequat ultricies mauris mi a metus. Phasellus congue, leo sed ultricies tristique, nunc libero tempor ligula, at varius mi nibh in nisi. Aliquam erat volutpat. Maecenas rhoncus, neque facilisis rhoncus tempus, elit ligula varius dui, quis amet.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /fourth section -->

  <!-- fifth section -->
  <div id="services" class="pad-section">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-center">
          <h3>Parallax scrolling effect is in action</h3>
          <h4>The next is the address on Google maps</h4>
        </div>
      </div>
    </div>
  </div>
  <!-- /fifth section -->

  <!-- google map -->
  <div id="google_map"></div>
  <!-- /google map -->

  <!-- footer -->
  <footer>
    <hr />
    <div class="container">
      <p class="text-right">Copyright &copy; Your Company 2014</p>
    </div>
  </footer>
  <!-- /footer -->


</body>
</html>

LaserSite/pages/templates/pages/navbar.html
   <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

LaserSite/userpolls/templates/userpolls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'userpolls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

LaserSite/userpolls/templates/userpolls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!--https://docs.djangoproject.com/en/1.8/intro/tutorial03/-->
        <li><a href="{% url 'userpolls: detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

LaserSite/userpolls/templates/userpolls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'userpolls:detail' question.id %}">Vote again?</a>